rootProject.name = "djl-serving"
include(":awscurl")
include(":benchmark")
include(":engines:python")
include(":jacoco")
include(":plugins:cache")
include(":plugins:kserve")
include(":plugins:management-console")
include(":plugins:plugin-management-plugin")
include(":plugins:secure-mode-plugin")
include(":plugins:static-file-plugin")
include(":prometheus")
include(":serving")
include(":wlm")
