name: djlbench
version: '0.22.1'
title: DJL Benchmark
license: Apache-2.0
summary: A machine learning benchmarking toolkit
description: |
  djl-bench is a command line tool that allows you to benchmark the
  model on all different platforms for single-thread/multi-thread
  inference performance.

  Currently djl-bench support the models from the following framework:
  - PyTorch
  - TensorFlow
  - Apache MXNet
  - PaddlePaddle
  - ONNXRuntime
  - TensorRT
  - TensorFlow Lite
  - XGBoost
  - LightGBM
  - Python

base: core18
grade: stable
confinement: classic

apps:
  djlbench:
    command: benchmark-$SNAPCRAFT_PROJECT_VERSION/bin/benchmark
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java-11-openjdk-amd64"
      PATH: "$SNAP/bin:$PATH:$SNAP/usr/lib/jvm/java-11-openjdk-amd64/bin"

parts:
  djlbench:
    plugin: gradle
    source: https://github.com/deepjavalibrary/djl-serving.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    gradle-output-dir: benchmark/build/libs
    gradle-options: [ -Pstaging, ':benchmark:dT' ]
    override-build: |
      snapcraftctl build
      tar xvf $SNAPCRAFT_PART_BUILD/benchmark/build/distributions/benchmark-*.tar -C $SNAPCRAFT_PART_INSTALL/
      rm -rf $SNAPCRAFT_PART_INSTALL/jar
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
