name: Credentials Test

on:
  pull_request:
    branches:
      - serving-publish  
  push:
    branches:
      - serving-publish 

permissions:
  id-token: write
  contents: read

jobs:
  test-aws-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::185921645874:role/github-actions-djl-serving
          aws-region: us-west-2
      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity
