name: Integration tests

on:
  workflow_dispatch:
    inputs:
      djl-version:
        description: 'The released version of DJL.'
        required: false
        default: ''
      tag-suffix:
        description: 'Run tests on the specific tags suffix i.e. arch-{suffix}'
        required: false
        type: string
        default: 'nightly'
  workflow_call:
    inputs:
      djl-version:
        description: 'The released version of DJL.'
        required: false
        type: string
        default: 'nightly'
      tag-suffix:
        description: 'Run tests on the specific tags suffix i.e. arch-{suffix}'
        required: false
        type: string
        default: ''

jobs:
  cpu-integration-tests:
    uses: ./.github/workflows/cpu-container-integration.yml
    secrets: inherit
    with:
      djl-version: ${{ github.events.inputs.djl-version }}
      tag-suffix: ${{ github.events.inputs.tag-suffix }}
  aarch64-integration-tests:
    uses: ./.github/workflows/aarch64-container-integration.yml
    secrets: inherit
    with:
      djl-version: ${{ github.events.inputs.djl-version }}
      tag-suffix: ${{ github.events.inputs.tag-suffix }}
  pytorch-gpu-integration-tests:
    uses: ./.github/workflows/pytorch-gpu-container-integration.yml
    secrets: inherit
    with:
      djl-version: ${{ github.events.inputs.djl-version }}
      tag-suffix: ${{ github.events.inputs.tag-suffix }}
