name: LMI Dist library Unit/Integration tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'


jobs:
  create-runners:
    runs-on: [self-hosted, scheduler]
    steps:
      - name: Create new G5 instance
        id: create_gpu
        run: |
          cd /home/ubuntu/djl_benchmark_script/scripts
          token=$( curl -X POST -H "Authorization: token ${{ secrets.ACTION_RUNNER_PERSONAL_TOKEN }}" \
          https://api.github.com/repos/deepjavalibrary/djl-serving/actions/runners/registration-token \
          --fail \
          | jq '.token' | tr -d '"' )
          ./start_instance.sh action_g5 $token djl-serving
    outputs:
      gpu_instance_id: ${{ steps.create_gpu.outputs.action_g5_instance_id }}


  integration-test:
    runs-on: [ self-hosted, g5 ]
    timeout-minutes: 60
    needs: create-runners
    container:
      image: deepjavalibrary/djl-serving:deepspeed-nightly
      options: --gpus all --runtime=nvidia --shm-size=2gb
    steps:
      - uses: actions/checkout@v3
      - name: Install environment
        working-directory: tests/integration
        run: |
          pip install https://publish.djl.ai/lmi_dist/lmi_dist-nightly-py3-none-any.whl


  stop-runners:
    if: always()
    runs-on: [ self-hosted, scheduler ]
    needs: [ create-runners, integration-test ]
    steps:
      - name: Stop all instances
        run: |
          cd /home/ubuntu/djl_benchmark_script/scripts
          instance_id=${{ needs.create-runners.outputs.gpu_instance_id }}
          ./stop_instance.sh $instance_id
