name: Nightly Docker image publish

on:
  workflow_dispatch:

jobs:
  create-runners:
    runs-on: [self-hosted, scheduler]
    steps:
      - name: Create new GPU instance
        id: create_gpu
        run: |
          cd /home/ubuntu/djl_benchmark_script/scripts
          token=$( curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
          https://api.github.com/repos/deepjavalibrary/djl-serving/actions/runners/registration-token \
          | jq '.token' | tr -d '"' )
          ./start_instance.sh action_gpu $token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  execute-runner:
    runs-on: [self-hosted, gpu]
    needs: create-runners
    steps:
      - name: Test GPU running
        run: |
          nvidia-smi

  stop-ruuners:
    if: always()
    runs-on: [self-hosted, scheduler]
    needs: execute-runners
    steps:
      - name: Stop all instances
        run: |
          cd /home/ubuntu/djl_benchmark_script/scripts
          instance_id=${{ create-runners.create_gpu.outputs.action_gpu_instance_id }}
          ./stop_instance.sh $instance_id


