name: Python Unit Tests

on:
  pull_request:
    paths:
      - "**.py"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: install Python Dependencies
        run: |
          cd engines/python/setup
          pip install -e ".[test]"
      - name: run pytests
        run: |
          cd engines/python/setup
          python -m unittest -v

